More e2e tests for Firefly projects
adobe/aio-lib-console pull request #18
Opened 2021-02-15 12:20 UTC by moritzraho

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-03-01 15:08 UTC, shazron requested changes
Some questions regarding the label for the tests not matching the actual test.

2021-03-01 15:08 UTC, shazron commented on e2e/e2e.js
> +  test('test createFireflyProject API with trailing spaces in title and description', async () => {
the title and description do not have trailing spaces here?

2021-03-01 15:08 UTC, shazron commented on e2e/e2e.js
> +      { name: fireflyProjectName, description: modifiedProjectDescription, title: 'modified project title', type: 'jaeger' }
the title and description do not have trailing spaces here?

2021-03-01 15:08 UTC, shazron commented on e2e/e2e.js
> +    const res = await sdkClient.createWorkspace(orgId, fireflyProjectId, { name: fireflyWorkspaceName, title: 'workspace title', description: workspaceDescription })
the title and description do not have trailing spaces here?

2021-03-01 16:43 UTC, moritzraho commented
oops forgot to remove the label as I moved all whitespace tests to the end of the file. Thanks @shazron, pushed a fix commit

2021-03-02 08:38 UTC, shazron approved these changes

2021-03-02 09:18 UTC, merged