Add XR apis to sdk
adobe/aio-lib-console pull request #20
Opened 2021-04-14 10:00 UTC by sandeep-paliwal

XR APIs for console sdk
TODO add e2e tests once APIs are live
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?
TODO

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-04-14 12:17 UTC, moritzraho requested changes
Looking good so far, quite a big change 🙂 

We need two more things to make this complete:
- e2e tests for the new endpoints, you can prepare them now but not run until ext reg is up
- remove old app registry apis
- also remove atlaspolicy apis

2021-04-15 06:11 UTC, sandeep-paliwal commented
Thanks @moritzraho for the comments.
I will add the e2e tests.
I guess old registry APIs we should deprecate, and once they are decommissioned, then we should remove them from SDK.
WDYT?

2021-04-15 08:42 UTC, moritzraho commented
@sandeep-paliwal good thoughts but no one is using this api in the sdk. We discussed this with @meryllblanchet and @fmeschbe I think it is safe to delete those apis.
+ app registry api will not be kept once moving to ext reg

2021-04-15 08:55 UTC, meryllblanchet commented
@sandeep-paliwal @moritzraho these APIs should not be exposed within the library and do not serve any 3rd party extensibility purpose. No deprecation needed IMO.

cc @fmeschbe

2021-04-20 05:03 UTC, sandeep-paliwal commented on src/index.js
> +  async getAllExtensionPoints (organizationId, xpId, options = {}) {
`xpId` was a required param as per the shared swagger spec. Anyway there is new spec available and we will need to make changes to SDK as per that.

2021-04-20 11:30 UTC, Himavanth commented on src/index.js
> +  async getAllExtensionPoints (organizationId, xpId, options = {}) {
Looks like there is no change to the param in this API. We should still make this change IMO.

2021-06-29 02:13 UTC, shazron commented
@sandeep-paliwal can you get this change into your PR branch: https://github.com/adobe/aio-lib-console/pull/21/files Jesse put it against master so it can't be merged via Github into this PR

2021-06-29 16:22 UTC, shazron commented
Moved to #22. Please review any pending changes due to review in this PR that needs to be migrated to the new PR.
The new PR now exists in the main repo, for publishing permission issues.

2021-06-29 16:22 UTC, closed without merging